--- 
title: "Reliable Construction of Matrix Population Models from Demographic Information"
author: "Bruce E. Kendall"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [Bibliography.bib]
biblio-style: apalike
link-citations: yes
---
\newcommand{\vect}[1]{\mathbf{#1}}



# Preface {-}


Matrix population models are powerful tools for quantitatively integrating demographic (births and deaths) and life history (aging, growth and development) information to address ecological questions as well as prioritizing management for rare, harvested, or invasive species. 
Over the past three decades, the number of animal and plant MPMs described and analyzed in the peer-reviewed literature has grown faster than linearly.
This growth can be attributed to two factors.
First, more studies are collecting complete demographic information on a population, either as an end in itself or as a side effect of other study objectives (e.g., evolutionary ecology studies that track fitness components throughout the lives of individuals and relatedness among individuals generate great demographic data).
Second, MPMs have been promoted (primarily by modellers) as an "easy" way to integrate demographic demographic information and draw novel conclusions from them.

Initially, most "empirical MPMs" (models of actual populations, as opposed to theoretical constructs) were created by collaborations between field biologists (who provided the data) and modellers (who took care of the mathematical details).
Subsequently, MPMs came to be viewed as DIY (do it yourself) models that any trained ecologist or conservation biologist could do, and many MPMs are now published without the assistance of an expert modeller.
It is true that the *conceptual* mapping of demographic and life history information to a projection matrix is (usually) straightforward.
But there are bookkeeping details (that affect the *quantititative* mapping) that are not biologically intuitive, and may be actively counter-intuitive.
When following the textbook approaches to MPM construction, getting these bookkeeping details just right can be tricky if one is not used to "thinking like a modeller."

Now, I am an ecological modeller, and as such I find the details of MPM bookkeeping intuitive.^[Basically, intuition in any subject is arrived at through repetition; I've built lots of models over the years!]
But I also have lots of experience in teaching MPMs to students who are new to modelling, and have noticed the places where they repeatedly have trouble accepting the need for, or even the validity of, the bookkeeping details.
When building their own models in class exercises, they often make mistakes in these places.
Furthermore, one of the class assignments is to work with a published MPM of the student's choice.
One year, every one of the models selected by the students had mistakes!^[Not only does this highlight the difficulty in correctly constructing MPMs, it says something disturbing about peer review....]
This inspired me to take a more systematic look at published MPMs.
Among animal MPMs, I found that between 35% and 60% (depending on the type of error) of published models were incorrectly formulated; and that the error rate was constant through time.^[These results were published in [Kendall et al. (2019) *Ecological Modelling* **406:** 33--43.](https://doi.org/10.1016/j.ecolmodel.2019.03.011)]
This led me to wonder if there was a more effective way to teach non-modellers how to construct MPMs.

The audience for this book is ecologists and conservation biologists whose focus is primarily empirical: you are used to collecting data and analyzing it using *statistical* models, but you are not well-versed in constructing and analyzing *mathematical* models.

The first goal of this book is to provide a gentle tutorial, and introduce a new approach to MPM construction that keeps you, the biolgist, focused on events in the life cycle of your organism, and uses the computer to integrate all the pieces into the model.

I start with the classic age-, size-, and stage-structured MPMs.

This approach is then expanded to incorporate richer biological detail into the model, such as extended pregnancy or periods when the offspring is dependent on its parents for survival.