# Introduction {#intro}

## What are matrix population models?
The population models that are taught in undergraduate ecology courses---the exponential growth model, logistic model, Ricker model, etc.---are useful for explaining and illustrating basic patterns in population dynamics, such as patterns of exponential growth, the effects of density dependence, and phenomena such as population cycles and chaos. 
Their utility stems from their simplicity, which allows them to be analyzed without recourse to pages of advanced math. 
In particular, most of these foundational models assume that all individuals in the population can be treated as if they have identical birth and death rates.

As a practicing ecologist or conservation biologist, you know first-hand that all individuals in a population are *not* identical: they age, develop, and grow; and birth and death rates (which I will collectively call "demography") often vary systematically with age, developmental stage, and size.
Individuals can differ in other important ways as well: for example, individuals of a given age may exhibit morphological variation resulting from genetic differences or heterogeneity in their developmental environment; or they might exhibit different behavioral responses to a given stimulus resulting from variation in prior experience.
These phenotypic differences can also affect demography.

Ultimately, an individual's short-term fitness (its survival probability or mortality risk, as well as its expected birth rate) depends on both its *state* (age, stage, or size), its *phenotype*, and the *environment* (encompassing abiotic conditions and resources as well other organisms with which it interacts) in which it lives.
Simple models that characterize the population simply by its abundance, density, or biomass cannot represent this biological richness; thus, they do no provide insight on whether this richness matters for population dynamics, or how it might be exploited to manage the population (e.g., to arrest the decline of a rare species).
On the other hand, a model that encompassed all of this, together with all of the feedback loops between the focal species and the ecological community it's embedded in, would be tremendously complex (browse any issue of the journal *Ecological Modelling* to see examples) and would require tremendous amounts of data to estimate all the parameters.

Matrix population models (MPMs) are a compromise with intermediate complexity.
They assume that individuals can be classified into a finite number of discrete states, and that an individual's state fully determines the individual's reproductive, survival, and growth rates in a given environment.

MPMs also use a discrete time step; this is usually one year for models of free-living organisms, but may be shorter or longer. 
Thus, the model implicitly integrates over events occuring within the time step.

In addition, the standard MPM assumes no density dependence in demography.
This allows access to a variety of analytic tools, but means that long-term projections should be taken with a large dash of salt.

The "matrix" in matrix population models does not have any biological meaning. 
Rather, it comes from use of matrix algebra to both make representation more compact and to give access to analytic and computational tools

The standard models only require information on survival fraction and mean birth rates across individuals within each class, as well as information on the probability that an individual moves from one class to another.
This information might be assembled in a life table, especially if the population is classified by age, but this is not a requirement.
This information can come from a variety of data sources, each with strengths and weaknesses (see chapter XX).
If you have data from a single year, or estimates that are multi-year averages, then you can construct a single matrix.
With estimates from multiple years, you can construct a matrix for each year, which allows you to construct a stochastic MPM that allows you to examine the effects of environmental variability.

## What are matrix population models used for?
You may be reading this book because you have collected demographic data on a population for some other objective, and a colleague or reviewer said "You should use that data to construct a matrix population model!"
Why would you want to do that?

Matrix population models have been extensively used in studies of life history evolution as well as for addressing management questions for endangered or invasive species (fisheries scientists tend not to use the MPM formalism for their age-structured models).
In the literature, we find that most MPMs are used to calculate the populations deterministic or stochastic asymptotic population growth rate, together with sensitivies of that growth rate to underlying model parameters.
The asymptotic growth rate, generally denoted $\lambda$ for deterministic MPMs and $\log \lambda_S$ for stochastic MPMs, can be viewed as an integrated measure of population performance (for population management problems) or as fitness (for evolutionary questions).
The sensitivities (and their cousins, elasticities) of the asymptotic growth rate provides information about the likely effect of a management intervention or response to selection, respectively.

Quite a few other quantities can be calculated from an MPM, and sensitivities of these quantities to various model components can be analyzed (@Caswell2019Book).
However, few of these have been taken up to the degree that the analysis of the asymptotic growth rate has.
Recent and ongoing comparative analyses of MPMs in the COMADRE and COMPADRE databases may reveal which of these analyses are particularly useful for various purposes.

## A brief history of matrix population models

## Common pitfalls in matrix population model construction
Summary of ideas and results in @Kendall2019.

## Mathematical essentials
### Notation
There is no getting around the fact that MPMs are mathematical constructs.
However, I will try to make the notation be as closely tied to the biology as possible. 
One challenge is that we need a consistent way to reference demographic rates of specific age, size, or stage classes.
In *mathematical* notation, $p_i$ is the survival rate of individuals in the $i$'th class.
Thus, for example, in an age-structured model with age classes 0, 1, 2, and so on, $p_2$ is the survival of one-year-olds.
In a stage-structured model with stage classes newborn, juvenile, sub-adult and adult, then $p_2$ is the survival of juveniles.
Keeping track of this mapping requires extra cognitive work, and can be especially confusing in age-structured models where the mathematical index and the biological age don't align.^[One could, of course, start the mathematical index at zero, and you will see this in some textbooks; but this leads to inconsistencies between age-structured and other models. It also doesn't work in R, where the indexing of a vector always starts at one.]
Thus I introduce a *biological* notation, in which the actual age or the name of the class is shown between parentheses in the subscript.
Thus, in an age-structured model, $p_{(2)}$ is the survival of two-year-olds (survival from age 2 to age 3).
In a stage-structured model, $p_{(\text{sub-adult})}$ is the annual survival of individuals who start the year in the sub-adult stage.

This distinction is also useful in referencing the vector of population abundances in year $t$, $\vect{n}(t)$. 
As we will see, MPMs can be constructed in different ways that either do or do not include newborn individuals in the population vector.
In that case, careful attention to context is required to know what $n_1(t)$ (the first element of $\vect{n}(t)$) refers to.
In contrast, $n_{(0)}(t)$ vs. $n_{(1)}(t)$, or $n_{(\text{newborn})}(t)$ vs. $n_{(\text{juvenile})}(t)$, is clear and unambiguous.

Transition notation

### Matrix multiplication

## Matrix population models in R

