# Stage-Structured Models

We now turn to models of populations in which developmental stage is a stronger determinant of demography than is age or size.
In the classical formulation, known as *Lefkovitch matrices*, an individual, if it survives, may either stay in its current stage or move to the next stage.
This creates a characteristic matrix shape in which the non-zero values comprise fertility coefficients across the top row, diagonal elements representing surviving and staying in the next stage, and sub-diagonal elements representing survival and maturation to the next stage (Fig. XXX).

To construct such models, we need to know how demography depends on stage: for each stage $i$, what is the birth rate ($b_i$) and survival rate ($p_i$)?
In addition, we need to know, of the individuals starting in stage $i$ that survive for a year, what fraction mature to stage $i+1$ by the end of the year?
We will call this value $g_i$, and name it the "maturation rate" (many texts and articles call this "growth," but I reserve that term for talking about increases in size).

Estimating the maturation rates properly is a somewhat subtle process, depending both on the biology of how individuals move through the developmental stages and on how the model will be used.
We will look at that in a later section of this chapter.
First, however, we will look at how to construct a matrix once you have all these values.

## The recipe
The stage-tructured model uses the same sort of birth and survival matrices ($\vect{B}$ and $\vect{P}$) as the age-structured model, so I encourage you to read Chapter \@ref(age-structured-models) before proceeding here.

### Ingredients
1. The name of the newborn stage (e.g., neonate, egg, seed) and a list of the $l$ subsequent developmental stages to include in the model.
This may be a subset of the actual developmental stages, if the species passes through multiple stages in a timestep (which is set by the breeding interval, and is typically one year).
For example, if a newborn fish starts as an egg and passes through the stages larva, swimming juvenile, settled juvenile in its first year, the first two stages in the model would be egg and settled juvenile, and the the survival and maturation rates would relate to survival from egg all the way to settled juvenile.
We will index the stages with $i$.
1. A list of annual survival rates (the fraction of individuals that survive for a year), one for each stage. 
Ideally, this will be survival from one birthay to the next (including from birth to the first birthday). 
If males and females have different survival rates, list the female values. 
We will call this list the vector $\vect{p}$, with elements $p_i$ being the annual survival rate (fraction of individuals surviving, regardles of which stage they end up in) of individuals that start in stage $i$.
2. A list of stage-specific birth rates: For each parental stage, the number of offspring per parent (counting both parents), or the number of female offspring produced by each female parent. 
We will call this list the vector $\vect{b}$, with elements $b_i$ being the number of offspring produced by a parent in stage $i$.
Newborns cannot reproduce, so there is no value of $b_0$.
3. A list of maturation rates (the fraction of surviving individuals in a stage that mature to the next stage), one for each stage.
We will call this list the vector $\vect{g}$, with elements $g_i$ being the the fraction of surviving individuals in stage $i$ maturing to stage $i+1$.
The remaining fraction ($1-g_i$) stays in stage $i$.
The maturation rate is conditioned on survival, so the fraction of individuals in stage $i$ in one year that are alive and in stage $i+1$ the next year would be $p_i g_i$.